dist: xenial
git: 
 depth: false

addons:
  sonarcloud:
    organization: kimfml
    token:
      secure: ••••••••••••••••

#test

language: python

cache: pip

notifications:
  email: false

python:
- 3.8.1

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
- pip install --upgrade pip tox
- pip install pytest-mock
- pip install pytest-asyncio
- pip install -e .
- pip install ."[tests]"
- pip install coverage
- pip install setuptools
- pip install pytest-cov

script:
# - tox
- pytest --cov-report term --cov-report xml:cov.xml --cov=test tests/
- pytest --junitxml=pytest-report.xml
# - sonar-scanner
 
